# (c) 2019 Aaron Taylor <ataylor at subgeniuskitty dot com>
# See LICENSE.txt file for copyright and license details.

all: test

test:
	@echo "Testing stdlib:"
	@./vv_test.py

clean:
	@rm -f ./test.vvs ./test.pvvs
